### ISSUE TITLE
path 권한 설정

### ISSUE THREAD

**Issue by annahxxl** [Team-kiwing/Team-3seco-kiwing-be#59]

**Comment by KarmaPol** [comment]
### security exception @ControllerAdvice 핸들링
https://colabear754.tistory.com/172#왜_스프링_시큐리티_예외는_@ControllerAdvice에서_처리할_수_없을까
-> 200 OK만 출력된다

### 필터 자체를 만드는 법
https://inkyu-yoon.github.io/docs/Language/SpringBoot/FilterExceptionHandle

**Comment by annahxxl** [comment]
@KarmaPol 이거 JwtAuthenticationEntryPoint, JwtAccessDeniedHandler 에서 바로 ErrorResponse 포맷으로 예외 던져주면 안되나요?
